version: "3.9"
services:
 system-service:
  image: r0819654/herexamen-proect-api-development
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: